apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordstatesimulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: passwordstatesimulator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: passwordstatesimulator
    spec:
      dnsConfig:
        options:
          - name: single-request-reopen
      containers:
        - name: passwordstatesimulator
          image: %%image%%
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: LISTEN_URL
              value: %%url%%
            - name: ALWAYS_NEW_DATA
              value: true
