apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordstate-operator
  labels:
    app: passwordstate-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordstate-operator
  template:
    metadata:
      labels:
        app: passwordstate-operator
    spec:
      containers:
        - name: passwordstate-operator
          image: %%image%%
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "%%environment%%"
            - name: SERVER_BASE_URL
              value: "%%serverBaseUrl%%"
            - name: API_KEY_SECRET_NAME
              value: "apikey"
            - name: API_KEY_SECRET_NAMESPACE
              value: "%%apiKeySecretNamespace%%"
            - name: SYNC_INTERVAL_SECONDS
              value: "%%syncIntervalSeconds%%"
---
apiVersion: v1
kind: Secret
metadata:
  name: "apikey"
stringData:
  apikey: "%%apikey%%"